routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth', 'auth.multiple_roles:admin,user,assistante sociale', 'cors'])->group(function() {
	Route::post('/prospect/home_status/getRequirements/{id}', 'ProspectController@home_status');
	Route::post('/prospect/getInfos', 'ProspectController@getInfos');
	Route::post('/prospect/dimensions', 'ProspectController@getDimensions');
	Route::get('/prospect/edit/{id}', 'ProspectController@edit')->name('edit');
	Route::post('/prospect/edit/{id}', 'ProspectController@update')->name('update');
	Route::put('/prospect/edit/password/{id}', 'ProspectController@updatePwd')->name('updatePwd');
	Route::put('/prospect/edit/mail/{id}', 'ProspectController@updateMail')->name('updateMail');
	Route::put('/prospect/edit/reference/{id}', 'ProspectController@updateReference')->name('updateReference');
	Route::put('/prospect/edit/{id}/{idUser}', 'ProspectController@updateficheInstall')->name('updateficheInstall');
	Route::delete('/prospect/delete/{id}', 'ProspectController@destroy')->name('destroy');
	Route::post('/prospect/export/{id}', 'ProspectController@export')->name('prospect.export');
	Route::put('/prospect/home_status/{id}', 'ProspectController@updateHomeStatus')->name('updateHomeStatus');
	Route::put('/prospect/documents/{id}', 'ProspectController@updateDocuments')->name('updateDocuments');
	Route::get('/prospect/create', 'ProspectController@index')->name('prospect.create');
	Route::post('/prospect/create', 'ProspectController@create');
});

Route::middleware(['auth', 'auth.multiple_roles:admin,user'])->group(function() {
	Route::post('/prospect/updateSigns/{id}', 'ProspectController@updateSigns');
});

Route::middleware(['auth', 'auth.admin'])->namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
	Route::resource('/users', 'UserController', ['except' => ['show', 'create', 'edit']]);
	Route::resource('/status', 'StatusController', ['except' => ['show', 'edit', 'create']]);
	Route::resource('/sources', 'SourceController', ['except' => ['show', 'edit', 'create']]);
	Route::post('/status/order', 'StatusController@updateOrder');
});

Route::middleware('auth')->group(function() {
	Route::get('/home', function(){
		return redirect()->route('home');
	});
	Route::get('/prospect/read', function(){
		return view('prospects.chooseOne');
	})->name('home');
	Route::get('/', function() {
		return redirect()->route('home');
	});
	Route::delete('/prospect/deleteDocs/{id}/{doc}', 'ProspectController@deleteDocs')->name('deleteDocs');
	Route::post('/prospect/addDocs/{id}', 'ProspectController@addDocs')->name('addDocs');
	Route::post('/prospect/read', 'ProspectController@readAll');
	Route::get('/prospect/read/{id}', 'ProspectController@read')->name('read');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	
});

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    protected $fillable = [
        "name"
    ];
}

app/Http/Controllers/Admin/StatusController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;

class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.status.index')->with('status', DB::table('status')->orderBy('order')->get());
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!DB::table('status')->where('name', $request->name)->first()){
            DB::table('status')->insert(['name' => $request->name, 'order' => DB::table('status')->max('order')+1]);
            return redirect()->back()->with('success', 'Le status '.$request->name.' a bien été créer !');
        }
        return redirect()->back()->with('error', 'Le status '.$request->name.' existe déjà !');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('status')->where('id', $id)->update(['name' => $request->name]);
        return redirect()->back()->with('success', 'Le status à bien été modifier');
    }

    public function updateOrder(Request $request){
        foreach ($request->object as $key => $value) {
            DB::table('status')->where('id', $key)->update(['order' => intval($value)]);
        }
        return true;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $order = DB::table('status')->where('id', $id)->pluck('order')->first();
        if($order !== null){
            $array = DB::table('status')->where('order', '>', $order)->orderBy('order')->pluck('order', 'id')->toArray();
            foreach ($array as $key => $value) {
                DB::table('status')->where('id', $key)->update(['order' => $value - 1]);
            }
        }
        DB::table('status')->where('id', $id)->delete();
        return redirect()->back()->with('success', 'Votre status à bien été supprimer !');
    }
}

resources/views/admin/status/index.blade.php
@extends('layouts.app')
@section('content')    
@include('users.partials.header', [
        'title' => __('Hello') . ' '. auth()->user()->name,
        'description' => __('Ici vous pouvez gérer tous les status. Bien sûr, seulement les administrateurs ont accés à cette page. Vous pouvez modifier, supprimer, créer et même modifier l\'ordre des status !'),
        'img' => 'folder-cover.jpg'
    ]) 
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col mb-5 mb-xl-0">
                <div class="card bg-white">
                    <div class="card-header bg-white border-0">
                        <div class="align-items-center">
                            @if (\Session::has('success'))
                                <div class="alert alert-success" role="alert">
                                    {!! \Session::get('success') !!}
                                </div>
                            @elseif(\Session::has('error'))
                                <div class="alert alert-danger" role="alert">
                                    {!! \Session::get('error') !!}
                                </div>
                            @endif
                            <div class="row">
                                <div class="col-lg-6 text-left">
                                    <h1>La liste des status</h1>
                                    <p class="text-danger">ATTENTION ! Supprimer un statut, supprimera toutes les fiches qui ont le statut supprimé !</p>
                                </div>
                                <div class="col-lg-6 text-right">
                                    <button class="btn btn-info" data-toggle="modal" data-target="#addUserModal">Ajouter un status</button>
                                    <div class="modal fade text-left" id="addUserModal" tabindex="-1" role="dialog" aria-labelledby="addUserModalLabel" aria-hidden="true">
                                        <form action="{{route('admin.status.store')}}" method="post">
                                            {{ csrf_field() }}
                                            <div class="modal-dialog modal-lg" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="addUserModalLabel">Ajouter un status</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true">&times;</span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                    <input type="text" name="name" id="statuName" placeholder="Nom du status" class="form-control"  onkeyup="this.value = this.value.toUpperCase();">
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    <button type="submit" class="btn btn-primary">Créer le status</button>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <div class="card-body">
                        <table class="table table-responsive" id='table'>
                            <thead class="thead-light">
                                <tr>
                                    <th class="text-left">#</th>
                                    <th class="text-left" width="100%">Status</th>
                                    <th class="text-right" width="15%">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="list">
                                @foreach ($status as $statu)
                                    <tr>
                                        <input class='handle text-center' type="hidden" value='{{$statu->id}}'>
                                        <th class='handle text-left'>{{$statu->order}}</th>
                                        <th class='handle text-left'>{{$statu->name}}</th>
                                        <th class="text-right">
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#statu{{$statu->id}}EditModal">
                                                <i class="fas fa-user-edit"></i>
                                            </button>
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#statu{{$statu->id}}DeleteModal">
                                                <i class="fas fa-user-times"></i>
                                            </button>
                                        </th>
                                    </tr>
                                    {{-- Edit modal --}}
                                    <div class="modal fade text-left" id="statu{{$statu->id}}EditModal" tabindex="-1" role="dialog" aria-labelledby="statu{{$statu->id}}EditModalLabel" aria-hidden="true">
                                        <form action="{{route('admin.status.update', $statu->id)}}" method="post">
                                            {{ csrf_field() }}
                                            @method('put')
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="statu{{$statu->id}}EditModalLabel">Modifier le status {{$statu->name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true">&times;</span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                        <label for="statu{{$statu->id}}Name" class="form-control-label">Nom :</label>
                                                        <input type="text" name="name" id="statu{{$statu->id}}Name" value="{{$statu->name}}" class="form-control"  onkeyup="this.value = this.value.toUpperCase();">
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    <button type="submit" class="btn btn-primary">Sauvegarder</button>
                                                  </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    {{-- Delete modal --}}
                                    <div class="modal fade text-left" id="statu{{$statu->id}}DeleteModal" tabindex="-1" role="dialog" aria-labelledby="statu{{$statu->id}}DeleteModalLabel" aria-hidden="true">
                                        <form action="{{route('admin.status.destroy', $statu->id)}}" method="post">
                                            {{ csrf_field() }}
                                            @method('delete')
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="statu{{$statu->id}}DeleteModalLabel">Supprimer définitivement le status {{$statu->name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true">&times;</span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                    <p class="text-danger">Attention ! Vous êtes sur le point de supprimer définitvement le status {{$statu->name}}, êtes vous sûr ?</p>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    <button type="submit" class="btn btn-danger">Supprimer</button>
                                                  </div>
                                                </div>
                                              </div>
                                        </form>
                                    </div>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection
@section('scripts')
<script src="{{asset('js/table-dragger.min.js?ver=1.1')}}"></script>
<script src="{{asset('js/status.js?ver=1.1')}}"></script>
@endsection