routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth', 'auth.multiple_roles:admin,user,assistante sociale', 'cors'])->group(function() {
	Route::post('/prospect/home_status/getRequirements/{id}', 'ProspectController@home_status');
	Route::post('/prospect/getInfos', 'ProspectController@getInfos');
	Route::post('/prospect/dimensions', 'ProspectController@getDimensions');
	Route::get('/prospect/edit/{id}', 'ProspectController@edit')->name('edit');
	Route::post('/prospect/edit/{id}', 'ProspectController@update')->name('update');
	Route::put('/prospect/edit/password/{id}', 'ProspectController@updatePwd')->name('updatePwd');
	Route::put('/prospect/edit/mail/{id}', 'ProspectController@updateMail')->name('updateMail');
	Route::put('/prospect/edit/reference/{id}', 'ProspectController@updateReference')->name('updateReference');
	Route::put('/prospect/edit/{id}/{idUser}', 'ProspectController@updateficheInstall')->name('updateficheInstall');
	Route::delete('/prospect/delete/{id}', 'ProspectController@destroy')->name('destroy');
	Route::post('/prospect/export/{id}', 'ProspectController@export')->name('prospect.export');
	Route::put('/prospect/home_status/{id}', 'ProspectController@updateHomeStatus')->name('updateHomeStatus');
	Route::put('/prospect/documents/{id}', 'ProspectController@updateDocuments')->name('updateDocuments');
	Route::get('/prospect/create', 'ProspectController@index')->name('prospect.create');
	Route::post('/prospect/create', 'ProspectController@create');
});

Route::middleware(['auth', 'auth.multiple_roles:admin,user'])->group(function() {
	Route::post('/prospect/updateSigns/{id}', 'ProspectController@updateSigns');
});

Route::middleware(['auth', 'auth.admin'])->namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
	Route::resource('/users', 'UserController', ['except' => ['show', 'create', 'edit']]);
	Route::resource('/status', 'StatusController', ['except' => ['show', 'edit', 'create']]);
	Route::resource('/sources', 'SourceController', ['except' => ['show', 'edit', 'create']]);
	Route::post('/status/order', 'StatusController@updateOrder');
});

Route::middleware('auth')->group(function() {
	Route::get('/home', function(){
		return redirect()->route('home');
	});
	Route::get('/prospect/read', function(){
		return view('prospects.chooseOne');
	})->name('home');
	Route::get('/', function() {
		return redirect()->route('home');
	});
	Route::delete('/prospect/deleteDocs/{id}/{doc}', 'ProspectController@deleteDocs')->name('deleteDocs');
	Route::post('/prospect/addDocs/{id}', 'ProspectController@addDocs')->name('addDocs');
	Route::post('/prospect/read', 'ProspectController@readAll');
	Route::get('/prospect/read/{id}', 'ProspectController@read')->name('read');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	
});

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <img src="{{ asset('argon') }}/img/brand/logo-copie.jpg" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/logo-copie.jpg">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Navigation -->
            <ul class="navbar-nav">
                @hasrole('admin')
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.sources.index') }}">
                            <i class="fas fa-user-tag text-warning"></i> {{ __('Gérer les sources') }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.users.index') }}">
                            <i class="ni ni-circle-08 text-success"></i> {{ __('Gérer les utilisateurs') }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.status.index') }}">
                            <i class="ni ni-tag text-primary"></i> {{ __('Gérer les statuts') }}
                        </a>
                    </li>
                @endhasrole
                @hasroles(['admin', 'user', 'Assistante sociale'])
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('prospect.create') }}">
                            <i class="ni ni-fat-add text-danger"></i> {{ __('Créer une fiche client') }}
                        </a>
                    </li>
                @endhasroles
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-archive-2 text-info"></i> {{ __('Voir les fiches clients') }}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>