routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth', 'auth.multiple_roles:admin,user,assistante sociale', 'cors'])->group(function() {
	Route::post('/prospect/home_status/getRequirements/{id}', 'ProspectController@home_status');
	Route::post('/prospect/getInfos', 'ProspectController@getInfos');
	Route::post('/prospect/dimensions', 'ProspectController@getDimensions');
	Route::get('/prospect/edit/{id}', 'ProspectController@edit')->name('edit');
	Route::post('/prospect/edit/{id}', 'ProspectController@update')->name('update');
	Route::put('/prospect/edit/password/{id}', 'ProspectController@updatePwd')->name('updatePwd');
	Route::put('/prospect/edit/mail/{id}', 'ProspectController@updateMail')->name('updateMail');
	Route::put('/prospect/edit/reference/{id}', 'ProspectController@updateReference')->name('updateReference');
	Route::put('/prospect/edit/{id}/{idUser}', 'ProspectController@updateficheInstall')->name('updateficheInstall');
	Route::delete('/prospect/delete/{id}', 'ProspectController@destroy')->name('destroy');
	Route::post('/prospect/export/{id}', 'ProspectController@export')->name('prospect.export');
	Route::put('/prospect/home_status/{id}', 'ProspectController@updateHomeStatus')->name('updateHomeStatus');
	Route::put('/prospect/documents/{id}', 'ProspectController@updateDocuments')->name('updateDocuments');
	Route::get('/prospect/create', 'ProspectController@index')->name('prospect.create');
	Route::post('/prospect/create', 'ProspectController@create');
});

Route::middleware(['auth', 'auth.multiple_roles:admin,user'])->group(function() {
	Route::post('/prospect/updateSigns/{id}', 'ProspectController@updateSigns');
});

Route::middleware(['auth', 'auth.admin'])->namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
	Route::resource('/users', 'UserController', ['except' => ['show', 'create', 'edit']]);
	Route::resource('/status', 'StatusController', ['except' => ['show', 'edit', 'create']]);
	Route::resource('/sources', 'SourceController', ['except' => ['show', 'edit', 'create']]);
	Route::post('/status/order', 'StatusController@updateOrder');
});

Route::middleware('auth')->group(function() {
	Route::get('/home', function(){
		return redirect()->route('home');
	});
	Route::get('/prospect/read', function(){
		return view('prospects.chooseOne');
	})->name('home');
	Route::get('/', function() {
		return redirect()->route('home');
	});
	Route::delete('/prospect/deleteDocs/{id}/{doc}', 'ProspectController@deleteDocs')->name('deleteDocs');
	Route::post('/prospect/addDocs/{id}', 'ProspectController@addDocs')->name('addDocs');
	Route::post('/prospect/read', 'ProspectController@readAll');
	Route::get('/prospect/read/{id}', 'ProspectController@read')->name('read');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	
});

app/Http/Controllers/Admin/SourceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;

class SourceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sources = DB::table('prospect_sources')->get()->all();
        return view('admin.sources.index', ['sources' => $sources]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!DB::table('prospect_sources')->where('name', $request->name)->first()){
            DB::table('prospect_sources')->insert(['name' => $request->name]);
            return redirect()->back()->with('success', 'Le status '.$request->name.' a bien été créer !');
        }
        return redirect()->back()->with('error', 'La source '.$request->name.' existe déjà !');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('prospect_sources')->where('id', $id)->update(['name' => $request->name]);
        return redirect()->back()->with('success', 'La source à bien été modifier');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('prospect_sources')->where('id', $id)->delete();
        return redirect()->back()->with('success', 'Votre source à bien été supprimer !');
    }
}

resources/views/admin/sources/index.blade.php
@extends('layouts.app')
@section('content')    
@include('users.partials.header', [
        'title' => __('Hello') . ' '. auth()->user()->name,
        'description' => __('Ici vous pouvez gérer tous les sources. Bien sûr, seulement les administrateurs ont accés à cette page. Vous pouvez modifier, supprimer, créer et même modifier l\'ordre des sources !'),
        'img' => 'folder-cover.jpg'
    ]) 
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col mb-5 mb-xl-0">
                <div class="card bg-white">
                    <div class="card-header bg-white border-0">
                        <div class="align-items-center">
                            @if (\Session::has('success'))
                                <div class="alert alert-success" role="alert">
                                    {!! \Session::get('success') !!}
                                </div>
                            @elseif(\Session::has('error'))
                                <div class="alert alert-danger" role="alert">
                                    {!! \Session::get('error') !!}
                                </div>
                            @endif
                            <div class="row">
                                <div class="col-lg-6 text-left">
                                    <h1>La liste des sources</h1>
                                    <p class="text-danger">ATTENTION ! Supprimer une source, supprimera toutes les fiches qui ont la source  supprimé !</p>
                                </div>
                                <div class="col-lg-6 text-right">
                                    <button class="btn btn-info" data-toggle="modal" data-target="#addSourceModal">Ajouter une source</button>
                                    <div class="modal fade text-left" id="addSourceModal" tabindex="-1" role="dialog" aria-labelledby="addSourceModalLabel" aria-hidden="true">
                                        <form action="{{route('admin.sources.store')}}" method="post">
                                            {{ csrf_field() }}
                                            <div class="modal-dialog modal-lg" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="addSourceModalLabel">Ajouter une source</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true">&times;</span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                    <input type="text" name="name" id="sourceName" placeholder="Nom de la source" class="form-control" required>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    <button type="submit" class="btn btn-primary">Créer la source</button>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <div class="card-body">
                        <table class="table w-100 dt-table responsive display nowrap" id='table'>
                            <thead class="thead-light">
                                <tr>
                                    <th class="text-left">#</th>
                                    <th class="text-left">Sources</th>
                                    <th class="text-right" width="15%">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="list">
                                @foreach ($sources as $source)
                                    <tr>
                                        <th class='handle text-left'>{{$source->id}}</th>
                                        <th class='handle text-left'>{{$source->name}}</th>
                                        <th class="text-right">
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#source{{$source->id}}EditModal">
                                                <i class="fas fa-user-edit"></i>
                                            </button>
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#source{{$source->id}}DeleteModal">
                                                <i class="fas fa-user-times"></i>
                                            </button>
                                        </th>
                                    </tr>
                                    {{-- Edit modal --}}
                                    <div class="modal fade text-left" id="source{{$source->id}}EditModal" tabindex="-1" role="dialog" aria-labelledby="source{{$source->id}}EditModalLabel" aria-hidden="true">
                                        <form action="{{route('admin.sources.update', $source->id)}}" method="post">
                                            {{ csrf_field() }}
                                            @method('put')
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="source{{$source->id}}EditModalLabel">Modifier la source {{$source->name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true">&times;</span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                        <label for="source{{$source->id}}Name" class="form-control-label">Nom :</label>
                                                        <input type="text" name="name" id="source{{$source->id}}Name" value="{{$source->name}}" class="form-control">
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    <button type="submit" class="btn btn-primary">Sauvegarder</button>
                                                  </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    {{-- Delete modal --}}
                                    <div class="modal fade text-left" id="source{{$source->id}}DeleteModal" tabindex="-1" role="dialog" aria-labelledby="source{{$source->id}}DeleteModalLabel" aria-hidden="true">
                                        <form action="{{route('admin.sources.destroy', $source->id)}}" method="post">
                                            {{ csrf_field() }}
                                            @method('delete')
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="source{{$source->id}}DeleteModalLabel">Supprimer définitivement le sources {{$source->name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true">&times;</span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                    <p class="text-danger">Attention ! Vous êtes sur le point de supprimer définitvement le sources {{$source->name}}, êtes vous sûr ?</p>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                                    <button type="submit" class="btn btn-danger">Supprimer</button>
                                                  </div>
                                                </div>
                                              </div>
                                        </form>
                                    </div>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection
@section('scripts')
<script src="{{asset('js/tables.js?ver=1.1')}}"></script>
@endsection